### ISSUE TITLE
Denoicing

### ISSUE THREAD

**Issue by mmints** [linusmossberg/monte-carlo-ray-tracer#2]
Hej Linus,

Great work and thanks for sharing!
I've a question about the images that you present in the `readme`. Those are denoiced. Did I miss an implementation in you repo, or did you applied some additional denoicing on the output images?

**Comment by linusmossberg** [comment]
Thank you! No, none of the images have been denoised. They have been rendered using a much higher sample count (`sqrtspp`) than what is currently set in the scene files. I've set `sqrtspp` fairly low in the scene files to provide fast previews, since rendering with higher sample counts can take several hours.

**Comment by odil24** [comment]
@linusmossberg can you post your PC characteristics? Cpu? Render times and etc? Render settings also too?

Thanks.

**Comment by linusmossberg** [comment]
@odil24 I used an Intel 3770K to render the images in the readme, but I don't have detailed information about the sample counts or render times for any of them. The coffee maker scene renders in 22 seconds at roughly 500 000 samples per second with the current settings.

**Comment by mmints** [comment]
Thanks for the quick reply! You should add this info to your `readme` in the Scene Format section ^^
Off-Topic to the initial topic of this issue: are you thinking about to include `glTF` as a file format for scenes? I'm just curious because your using json for serializing of the scene params. With glTF your scene sources would rely only on json.

**Comment by linusmossberg** [comment]
@uneron I've written about the `sqrtspp` option under Scene Format/Cameras in the main readme, but mentioning that the scene files uses preview settings by default in `scenes/README.md` seems like a good idea.

I hadn't considered glTF but it sounds interesting, so maybe in the future. This project has mostly been developed for learning purposes, so I've intentionally used a minimal amount of external libraries.

**Comment by mmints** [comment]
Oh yes, I see!

Anyway, thanks for sharing your work!
I'm currently going through _the_ PBR book and your repo helps a lot 👍
