### ISSUE TITLE
Can we bring it to Cuda?

### ISSUE THREAD

**Issue by whatisor** [linusmossberg/monte-carlo-ray-tracer#4]
CPU is too slow for this.
We should bring this to Cuda like Optix?

**Comment by linusmossberg** [comment]
It would require a lot of refactoring, but yes it's possible. I implemented a GPU version of [Monte Carlo Geometry Processing](https://www.cs.cmu.edu/~kmcrane/Projects/MonteCarloGeometryProcessing/index.html) in CUDA for my master thesis that has a very similar structure to this program.

I have no plans to do so right now however and I would likely create a separate repository if so, unless I find a very simple way of doing it that doesn't muddle up the CPU implementation.
