### ISSUE TITLE
How to make a sence by myself?

### ISSUE THREAD

**Issue by charles-wh** [linusmossberg/monte-carlo-ray-tracer#5]
Hi Linusmossberg,
I want to test some pbrt or obj scenes under this project, but I don't know how to convert and generate scene.json by myself.
Could you please give some advice such as how to convert pbrt material format to this project's material format? Thanks!

**Comment by odil24** [comment]
> Hi Linusmossberg, I want to test some pbrt or obj scenes under this project, but I don't know how to convert and generate scene.json by myself. Could you please give some advice such as how to convert pbrt material format to this project's material format? Thanks!

Hi. O've not any build myself so are you have custom build yourself? if so are you can upload here for win 10 x64? then we can try to create json file together

**Comment by charleswh** [comment]
@odil24 
Hi, my requirement maybe simple, such as this scene： Country Kitchen @ https://benedikt-bitterli.me/resources/.
I want to convert this scene to this project's scene json format, but i don't know how to convert the material fields.
Thanks.

**Comment by linusmossberg** [comment]
The readme has lots of information on scene creation. Tungsten/Mitsuba/pbrt have more features however, so it may not be possible to convert some scenes to my format completely. I have for example not implemented textures, which is a very limiting factor.
